version: "3"

services:
    db:
        image: postgres:16
        container_name: pg
        restart: always
        environment:
            POSTGRES_USER: appuser
            POSTGRES_PASSWORD: pass123
            POSTGRES_DB: bot_db
        volumes:
            - pgdata:/var/lib/postgresql/data
            - ./db/init:/docker-entrypoint-initdb.d

    import:
        build: ./import
        container_name: import
        volumes:
            - ./import:/app
        working_dir: /app
        command: python import.py
        depends_on:
            - db
    
    bot:
        build: ./bot
        container_name: bot
        env_file: .env
        depends_on:
            - db
            - import

    
volumes:
  pgdata: